name: EmbeddedMiddle-CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "CI start"

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        pwd
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libmosquittopp-dev
        ls -al
        make

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: |
          pwd
          ls -al

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build tests
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libmosquittopp-dev
          make test

      - name: Exec tests
        run: |
          ./build/test/oalloc_test
          ./build/test/fail_test
          
