name: EmbeddedMiddle-CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "CI start"
    - uses: actions/checkout@v2
    - run: |
        pwd
        apt-get install -y libcurl4-openssl-dev libmosquittopp-dev
        ls -al
        make
